[package]
name = "kumorust"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
reqwest = { version = "0.13", default-features = false, features = ["blocking", "native-tls"] }
url = "2"
windows = { git = "https://github.com/microsoft/windows-rs", rev = "79d8db43bbd38167941416cea2004dd3067e785a", features = [
    "ApplicationModel",
    "Data_Xml_Dom",
    "Foundation",
    "Management_Deployment",
    "System",
    "UI_Notifications",
    "appmodel",
    "combaseapi",
    "objidl",
    "objbase",
    "propidlbase",
    "propkey",
    "shobjidl_core",
    "winerror",
    "wtypes",
] }
windows-collections = { git = "https://github.com/microsoft/windows-rs", rev = "79d8db43bbd38167941416cea2004dd3067e785a" }
windows-reactor = { git = "https://github.com/microsoft/windows-rs", rev = "79d8db43bbd38167941416cea2004dd3067e785a" }
zip = { version = "8", default-features = false, features = ["deflate"] }

[build-dependencies]
windows-reactor-setup = { git = "https://github.com/microsoft/windows-rs", rev = "79d8db43bbd38167941416cea2004dd3067e785a" }
